Update 🍪 & 👍🏻 (20210726)
MajkiIT/polish-ads-filter pull request #20098
Opened 2021-07-26 22:16 UTC by PolishJarvis

### Witam szanownych panów!  <br><br>  <ul><li> fix #20096, fix #20095, fix #20094 i kilka zgłoszeń z repo AdGuard  <li> fix #20097 </ul>  <i> reszta czeka na potwierdzenie wyprawowania reklam lub chętnych na wycięcie (social wycięty z 15 dni temu w tamtych zgłoszeniach).</i>

2021-07-26 22:19 UTC, krystian3w approved these changes

2021-07-26 22:22 UTC, krystian3w commented
@hawkeye116477 mała pomyłka z numerkiem wysłałem `20094` a powinno być #20093

2021-07-26 22:23 UTC, krystian3w requested changes
zamknie się złe zgłoszenie o naprawie anty-adblock z "`redirect=noop.txt`"

2021-07-26 23:14 UTC, xxcriticxx commented
@krystian3w Ta gałąź zawiera konflikty, które należy rozwiązać

2021-07-27 09:32 UTC, hawkeye116477 commented
Przecież @xxcriticxx sam może edytować komentarz :smile:.

2021-07-27 11:00 UTC, merged

2021-07-27 21:14 UTC, krystian3w commented
Konfliktu nie mogłem podejrzeć, musiałbym używać chyba gita z konsoli.

2021-07-28 07:14 UTC, felix-22 commented
Ale https://github.com/MajkiIT/polish-ads-filter/issues/20094 to otworzyć z powrotem, bo zamknięte omyłkowo. A w ogóle czy ta omyłka to przypadkiem nie był zaplanowany sabotaż żeby mi po złości zrobić.

2021-07-28 18:04 UTC, felix-22 commented
Hmmm dopiero zauważyłem (przypadkiem), że komentarz został przeniesiony: https://github.com/MajkiIT/polish-ads-filter/issues/20091#issuecomment-887418672 więc wszystko jest ok, poza faktem że o tym przeniesieniu nie zostałem poinformowany...